name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Replace API Key
      run: |
        echo "Checking if OpenRouter API key secret exists..."
        if [ -n "${{ secrets.OPENROUTER_API_KEY }}" ]; then
          echo "OpenRouter API key secret found, replacing placeholder..."
          sed -i "s/OPENROUTER_API_KEY_PLACEHOLDER/${{ secrets.OPENROUTER_API_KEY }}/g" script.js
          echo "Verifying replacement..."
          if grep -q "OPENROUTER_API_KEY_PLACEHOLDER" script.js; then
            echo "ERROR: Placeholder still exists after replacement!"
            exit 1
          fi
          echo "OpenRouter API key replacement successful!"
        else
          echo "OpenRouter API key secret not set, skipping replacement. App will prompt for manual entry."
        fi
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./