name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Replace API Key
      run: |
        echo "Checking if API key secret exists..."
        if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
          echo "ERROR: GEMINI_API_KEY secret is not set!"
          exit 1
        fi
        echo "API key secret found, replacing placeholder..."
        sed -i "s/GEMINI_API_KEY_PLACEHOLDER/${{ secrets.GEMINI_API_KEY }}/g" script.js
        echo "Verifying replacement..."
        if grep -q "GEMINI_API_KEY_PLACEHOLDER" script.js; then
          echo "ERROR: Placeholder still exists after replacement!"
          exit 1
        fi
        echo "API key replacement successful!"
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./